---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shell-operator-k8s-reconciler

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: shell-operator-k8s-reconciler
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["resourcequotas"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["limitranges"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]  
- apiGroups: ["argoproj.io"]
  resources: ["argocds"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]  
- apiGroups: ["argoproj.io"]
  resources: ["appprojects"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] 
- apiGroups: ["argoproj.io"]
  resources: ["applications"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]  
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: shell-operator-k8s-reconciler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: shell-operator-k8s-reconciler
subjects:
  - kind: ServiceAccount
    name: shell-operator-k8s-reconciler
    namespace: appinfra-k8s-reconciler
