---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shell-operator-ns-reconciler

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: shell-operator-ns-reconciler
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: shell-operator-ns-reconciler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: shell-operator-ns-reconciler
subjects:
  - kind: ServiceAccount
    name: shell-operator-ns-reconciler
    namespace: appinfra-ns-reconciler
